# Generated by Django 5.0.2 on 2024-02-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_backend', '0008_delete_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='quiz_score',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
