# Generated by Django 5.0.2 on 2024-02-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_backend', '0010_alter_test_test_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_name',
            new_name='language',
        ),
    ]
